package github

//Autogenerated https://mholt.github.io/json-to-go/

import (
	"time"
)
type RepositoryCommit struct {
	URL         string `json:"url"`
	Sha         string `json:"sha"`
	NodeID      string `json:"node_id"`
	HTMLURL     string `json:"html_url"`
	CommentsURL string `json:"comments_url"`
	Commit     *Commit `json:"commit"`
	Author 		*User `json:"author"`
	Committer *User `json:"committer"`
	Parents []*ParentCommit `json:"parents"`
}
type CommitAuthor struct {
	Name  string    `json:"name"`
	Email string    `json:"email"`
	Date  time.Time `json:"date"`
}

type Commit  struct {
	URL    		string `json:"url"`
	Author   	*CommitAuthor  `json:"author"`
	Committer 	*CommitAuthor `json:"committer"`
	Message 	string `json:"message"`
	Tree  		*Tree `json:"tree"`
	CommentCount int `json:"comment_count"`
	Verification *Verification `json:"verification"`
}
type Verification struct {
	Verified  bool        `json:"verified"`
	Reason    string      `json:"reason"`
	Signature interface{} `json:"signature"`
	Payload   interface{} `json:"payload"`
}

type Tree  struct {
	URL string `json:"url"`
	Sha string `json:"sha"`
} 

type User struct {
	Login             string `json:"login"`
	ID                int    `json:"id"`
	NodeID            string `json:"node_id"`
	AvatarURL         string `json:"avatar_url"`
	GravatarID        string `json:"gravatar_id"`
	URL               string `json:"url"`
	HTMLURL           string `json:"html_url"`
	FollowersURL      string `json:"followers_url"`
	FollowingURL      string `json:"following_url"`
	GistsURL          string `json:"gists_url"`
	StarredURL        string `json:"starred_url"`
	SubscriptionsURL  string `json:"subscriptions_url"`
	OrganizationsURL  string `json:"organizations_url"`
	ReposURL          string `json:"repos_url"`
	EventsURL         string `json:"events_url"`
	ReceivedEventsURL string `json:"received_events_url"`
	Type              string `json:"type"`
	SiteAdmin         bool   `json:"site_admin"`
}

type ParentCommit struct {
	URL string `json:"url"`
	Sha string `json:"sha"`
}

type CommitFile struct {
	Sha         string `json:"sha"`
	Filename    string `json:"filename"`
	Status      string `json:"status"`
	Additions   int    `json:"additions"`
	Deletions   int    `json:"deletions"`
	Changes     int    `json:"changes"`
	BlobURL     string `json:"blob_url"`
	RawURL      string `json:"raw_url"`
	ContentsURL string `json:"contents_url"`
	Patch       string `json:"patch"`
}

type CommitsComparison struct {
	URL          	string `json:"url"`
	HTMLURL     	string `json:"html_url"`
	PermalinkURL	string `json:"permalink_url"`
	DiffURL     	string `json:"diff_url"`
	PatchURL     	string `json:"patch_url"`
	BaseCommit   	*RepositoryCommit `json:"base_commit"`
	MergeBaseCommit *RepositoryCommit `json:"merge_base_commit"`
	Status       	string `json:"status"`
	AheadBy      	int    `json:"ahead_by"`
	BehindBy     	int    `json:"behind_by"`
	TotalCommits 	int    `json:"total_commits"`
	Commits      	[]*RepositoryCommit `json:"commits"`
	Files 			[]*CommitFile `json:"files"`
}
